version: 2.1
orbs:
    codecov: codecov/codecov@1.0.5
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - run: yarn install
            - run: yarn test
            - codecov/upload:
                  file: coverage/*.json
